name: Build docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '!examples/**'
      - '!packages/**'

jobs:
  test-docs-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.11.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "::set-output name=store_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-store.outputs.store_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm build docs --prod
